services:
    netgen.ezplatform_site.view_builder.content:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\View\Builder\ContentViewBuilder
        public: false
        arguments:
            - '@netgen.ezplatform_site.site'
            - '@ezpublish.api.repository'
            - '@ezpublish.view.configurator'
            - '@ezpublish.view.view_parameters.injector.dispatcher'

    netgen.ezplatform_site.ngcontent_view_provider.configured:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\View\Provider\Configured
        arguments:
            - '@netgen.ezplatform_site.ngcontent_view.matcher_factory'
            - '@netgen.ezplatform_site.query_type.query_definition_mapper'
            - '@netgen.ezplatform_site.redirect_resolver'
        tags:
            - { name: ezpublish.view_provider, type: 'Netgen\Bundle\EzPlatformSiteApiBundle\View\ContentView', priority: 110 }
        public: false

    netgen.ezplatform_site.redirect_resolver:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\View\Redirect\Resolver
        arguments:
            - '@netgen.ezplatform_site.redirect.parameter_processor'
            - '@router'
        public: false

    netgen.ezplatform_site.redirect.parameter_processor:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\View\Redirect\ParameterProcessor
        arguments:
            - '@netgen.ezplatform_site.named_object_provider'
        public: false

    netgen.ezplatform_site.ngcontent_view.matcher_factory:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\Matcher\MatcherFactory
        arguments:
            - '@?eZ\Bundle\EzPublishCoreBundle\Matcher\ViewMatcherRegistry'
            - '@ezpublish.api.repository'
            - 'eZ\Publish\Core\MVC\Symfony\Matcher\ContentBased'
            - '@ezpublish.config.resolver'
            - 'ngcontent_view'
        calls:
            - [setContainer, ["@service_container"]]
        public: false

    netgen.ezplatform_site.ngcontent_view_provider.default_configured:
        class: eZ\Bundle\EzPublishCoreBundle\View\Provider\Configured
        arguments:
            - '@netgen.ezplatform_site.ngcontent_view.default_matcher_factory'
        tags:
            - {name: ezpublish.view_provider, type: 'Netgen\Bundle\EzPlatformSiteApiBundle\View\ContentView', priority: 90}
        public: false

    netgen.ezplatform_site.ngcontent_view.default_matcher_factory:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\Matcher\MatcherFactory
        arguments:
            - '@?eZ\Bundle\EzPublishCoreBundle\Matcher\ViewMatcherRegistry'
            - '@ezpublish.api.repository'
            - 'eZ\Publish\Core\MVC\Symfony\Matcher\ContentBased'
            - '@ezpublish.config.resolver'
            - 'ngcontent_view_defaults'
        calls:
            - [setContainer, ["@service_container"]]
        public: false
